use_async: true
symbol: "EUR/USD"
provider: "twelvedata"
interval: "1min"
outputsize: 500

api_keys:
  twelvedata: "your_twelvedata_api_key"
  polygon: "YOUR_POLYGON_API_KEY"  # or set POLYGON_API_KEY env var
  alphavantage: "your_alpha_vantage_api_key"
  currencystack: "your_currencystack_api_key"
  tiingo: "your_tiingo_api_key"

mlflow_enabled: true
mlflow_experiment: RCS_Trading
