name: rcs_cnn_lstm_env
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib
  - scikit-learn>=1.0.0
  - cudatoolkit=11.8
  - cudnn=8.6.0
  - tensorflow-gpu>=2.8.0
  - pip
  - pip:
      - MetaTrader5
      - shap>=0.40.0
      - ta>=0.7.0
      - yfinance>=0.1.87
      - onnx>=1.12.0
      - onnxruntime-gpu>=1.12.0
      - tf2onnx>=1.13.0
